[project]
name = "pyfin-sentiment"
version = "0.1.0"
description = "Add a short description here"
authors = ["Moritz Wilksch <moritzwilksch@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
postinstall = "pip install --no-build-isolation -e ." 

[dependencies]
pip = ">=24.0,<25"
polars = ">=0.20.15,<0.21"
numpy = ">=1.26.4,<1.27"
scikit-learn = ">=1.4.1.post1,<1.4.2"


[feature.dev.dependencies]
pytest = ">=7.2.0,<8.2"
twine = ">=5.0.0,<5.1"

[environments]
dev = ["dev"]
